### ISSUE TITLE
XML / Posty, Kategorie

### ISSUE THREAD

**Issue by torzeszko** [sugester/API#1]
Dzień dobry,

W waszym API na stronie http://sugester.pl/api znalazłem możliwość wyświetlania XML'i  z postami etc.

Problem, że działa tylko to: GET http://NAZWA_FORUM.sugester.pl/app/posts/POST_ID.xml 

Stąd pytania:

Jak wyświelić listę wszystkich kategorii w XML?
Jak wyświetlić listę wszystkich Id postów w XML?
Jak znaleźć link do załącznika, który dodałem do posta?

Dziękuje i pozdrawiam.

**Comment by marcin** [comment]
Dzień dobry
ostatnio rozwijamy API tylko w JSON, posty oraz kategorie są dostępne pod adresami:
http://NAZWA_FORUM.sugester.pl/app.json - posty
http://NAZWA_FORUM.sugester.pl/app/categories.json - kategorie
(przyjmują też te same parametry filtrujące, które są dostępne w samej aplikacji www)

Jeśli jednak jest to bardzo istotne, aby był XML dla tych danych, to możemy go dodać (choć proponuję spróbować obsługiwać JSON, gdyż za jego pomocą można mieć dostęp do wszystkich danych w Sugesterze)
